/* Copied from backend/src/payload-types.ts by scripts/sync-payload-types.mjs.
 * Do not edit: run `npm run generate:types` in backend/, then `npm run types:sync` here. */
/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    people: Person;
    media: Media;
    frames: Frame;
    essays: Essay;
    albums: Album;
    walks: Walk;
    exhibitions: Exhibition;
    photocalls: Photocall;
    submissions: Submission;
    orders: Order;
    rsvps: Rsvp;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    walks: {
      essays: 'essays';
      frames: 'frames';
      albums: 'albums';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    frames: FramesSelect<false> | FramesSelect<true>;
    essays: EssaysSelect<false> | EssaysSelect<true>;
    albums: AlbumsSelect<false> | AlbumsSelect<true>;
    walks: WalksSelect<false> | WalksSelect<true>;
    exhibitions: ExhibitionsSelect<false> | ExhibitionsSelect<true>;
    photocalls: PhotocallsSelect<false> | PhotocallsSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    rsvps: RsvpsSelect<false> | RsvpsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    manifesto: Manifesto;
    membership: Membership;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    manifesto: ManifestoSelect<false> | ManifestoSelect<true>;
    membership: MembershipSelect<false> | MembershipSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  roles: ('admin' | 'editor' | 'member')[];
  /**
   * The public People profile this account edits. Set on activation.
   */
  profile?: (number | null) | Person;
  membershipPlan?: ('none' | 'monthly' | 'annual') | null;
  membershipStatus?: ('none' | 'active' | 'lapsed') | null;
  membershipExpires?: string | null;
  /**
   * First activation. Set once; the joining fee is charged only while this is empty.
   */
  memberSince?: string | null;
  /**
   * Opted in to occasional email from the collective. A preference only; no tool is connected yet.
   */
  newsletter?: boolean | null;
  pendingEmail?: string | null;
  pendingEmailToken?: string | null;
  pendingEmailExpires?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  name: string;
  slug?: string | null;
  /**
   * The member register number, rendered as № 0001. Assigned on activation from a sequence; a number typed by hand moves the sequence past it, so numbers are never reused.
   */
  memberNumber?: number | null;
  /**
   * The account that edits this profile. Set on activation; editors can link by hand.
   */
  owner?: (number | null) | User;
  /**
   * The member chose to appear on the public roster. Needs a portrait.
   */
  onRoster?: boolean | null;
  portrait?: (number | null) | Media;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  roleTitle?: string | null;
  /**
   * City, as the photographer wants it shown (Pretoria, Cape Town...). Optional; the site claims no city when empty.
   */
  basedIn?: string | null;
  /**
   * Part of the founding circle of the collective.
   */
  foundingCircle?: boolean | null;
  instagram?: string | null;
  website?: string | null;
  /**
   * Shown on the public page only when "Show contact" is on.
   */
  contactEmail?: string | null;
  /**
   * Photographer choice: show their own contact on the site. Off means enquiries route to the collective address.
   */
  showContact?: boolean | null;
  /**
   * Manual sort order on the People page (lowest first).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt text for accessibility.
   */
  alt?: string | null;
  /**
   * Photographer / source credit.
   */
  credit?: string | null;
  /**
   * Restricted files are only visible to the uploader and editors.
   */
  visibility?: ('public' | 'restricted') | null;
  uploadedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frames".
 */
export interface Frame {
  id: number;
  image: number | Media;
  photographer?: (number | null) | Person;
  /**
   * Use when the photographer has no People profile. Every frame must carry a credit.
   */
  creditOverride?: string | null;
  caption?: string | null;
  location?: string | null;
  year?: number | null;
  tags?: string[] | null;
  /**
   * Top picks rotate as the homepage lead frame. With none ticked, the newest frame leads.
   */
  topPick?: boolean | null;
  /**
   * Set when this frame was promoted from a photocall submission.
   */
  sourceSubmission?: (number | null) | Submission;
  /**
   * The walk this frame was made on, if any. Only walks that have already happened.
   */
  walk?: (number | null) | Walk;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  photocall: number | Photocall;
  /**
   * Set automatically from the logged-in user; empty for anonymous photocall entries. Never changes afterwards.
   */
  submitter?: (number | null) | User;
  /**
   * Anonymous entries: the photographer name as given.
   */
  submitterName?: string | null;
  /**
   * Anonymous entries: contact email. Editors only.
   */
  submitterEmail?: string | null;
  whereYouShoot?: string | null;
  title?: string | null;
  statement?: string | null;
  images: (number | Media)[];
  agreedToTerms: boolean;
  status?: ('submitted' | 'shortlisted' | 'published' | 'rejected') | null;
  /**
   * Feedback visible to the submitter.
   */
  reviewNotes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Editorial notes - never shown to the submitter.
   */
  internalNotes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photocalls".
 */
export interface Photocall {
  id: number;
  title: string;
  slug?: string | null;
  theme?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heroImage?: (number | null) | Media;
  opensAt?: string | null;
  closesAt?: string | null;
  maxImagesPerSubmission?: number | null;
  membersOnly?: boolean | null;
  /**
   * The submission terms: photographers keep copyright and grant the collective a non-exclusive licence. This text is required in writing before a call opens.
   */
  terms?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  status?: ('draft' | 'open' | 'judging' | 'closed') | null;
  /**
   * The essay published from this call, once it exists.
   */
  resultEssay?: (number | null) | Essay;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "essays".
 */
export interface Essay {
  id: number;
  title: string;
  slug?: string | null;
  /**
   * Short standfirst under the title.
   */
  deck?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  leadFrame?: (number | null) | Frame;
  /**
   * The photo sequence. Editorial range is 12-20 frames - shorter or longer is allowed but should be deliberate. Full bleed is a device: the opening frame and at most one turn in the middle.
   */
  sequence?:
    | (
        | {
            frame: number | Frame;
            captionOverride?: string | null;
            /**
             * At most two per essay; the hook enforces it.
             */
            fullBleed?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'frame';
          }
        | {
            left: number | Frame;
            right: number | Frame;
            captionOverride?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pair';
          }
        | {
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
      )[]
    | null;
  contributors?: (number | Person)[] | null;
  /**
   * The walk(s) this essay came out of. Only walks that have already happened.
   */
  walks?: (number | Walk)[] | null;
  relatedPhotocall?: (number | null) | Photocall;
  publishedDate?: string | null;
  tags?: string[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "walks".
 */
export interface Walk {
  id: number;
  title: string;
  slug?: string | null;
  /**
   * Start of the walk. Enter times in SAST (the picker uses your local time).
   */
  date: string;
  /**
   * When the walk wraps. Until then the walk stays on the site as the current walk.
   */
  endTime?: string | null;
  meetingPoint?: string | null;
  route?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * GeoJSON FeatureCollection: one LineString (the route, [lng, lat] pairs) plus optional Point features with a "name" property for landmark markers. Drives the interactive map on /walks. Workflow for producing one precisely: docs/ROUTES.md.
   */
  routeGeo?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  routeMap?: (number | null) | Media;
  capacity?: number | null;
  priceMember?: number | null;
  priceNonMember?: number | null;
  bookingUrl?: string | null;
  bookingStatus?: ('open' | 'full' | 'closed') | null;
  leader?: (number | null) | Person;
  heroImage?: (number | null) | Media;
  /**
   * Position in the published programme, date order. Rendered as № 001.
   */
  number?: number | null;
  /**
   * Essays published from this walk.
   */
  essays?: {
    docs?: (number | Essay)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  frames?: {
    docs?: (number | Frame)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  albums?: {
    docs?: (number | Album)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "albums".
 */
export interface Album {
  id: number;
  title: string;
  /**
   * One URL segment, made from the title when empty: /albums/<slug>. Slashes and spaces are folded into hyphens.
   */
  slug?: string | null;
  /**
   * A few lines on what this album is. Optional.
   */
  intro?: string | null;
  /**
   * Plain photographs, not frames: album images never enter the archive. The caption on the site is each file's alt text.
   */
  images: (number | Media)[];
  /**
   * The walk(s) these photographs are from. Only walks that have already happened.
   */
  walks?: (number | Walk)[] | null;
  photographer?: (number | null) | Person;
  /**
   * Use when the photographer has no People profile. Every album must carry a credit.
   */
  creditOverride?: string | null;
  date?: string | null;
  publishedDate?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exhibitions".
 */
export interface Exhibition {
  id: number;
  title: string;
  slug?: string | null;
  venue?: string | null;
  startDate?: string | null;
  endDate?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heroImage?: (number | null) | Media;
  frames?: (number | Frame)[] | null;
  relatedEssays?: (number | Essay)[] | null;
  partners?: string | null;
  status?: ('upcoming' | 'current' | 'past') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  user?: (number | null) | User;
  type?: ('membership' | 'walk') | null;
  plan?: ('monthly' | 'annual') | null;
  item?: (number | null) | Walk;
  /**
   * Total in rand, frozen at order time.
   */
  amount?: number | null;
  /**
   * The part of the amount that is the once-off joining fee.
   */
  joiningFee?: number | null;
  currency?: string | null;
  /**
   * What the member types as the EFT reference.
   */
  reference?: string | null;
  /**
   * Set to Paid when the EFT shows. That activates the membership.
   */
  status?: ('pending' | 'paid' | 'failed' | 'cancelled' | 'refunded') | null;
  /**
   * Left empty, it is set when the status becomes paid.
   */
  paidAt?: string | null;
  coveredFrom?: string | null;
  coveredUntil?: string | null;
  provider?: ('payfast' | 'manual') | null;
  providerRef?: string | null;
  /**
   * Who confirmed the EFT, and when.
   */
  note?: string | null;
  /**
   * Raw provider payload for auditing.
   */
  raw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rsvps".
 */
export interface Rsvp {
  id: number;
  walk: number | Walk;
  /**
   * Set when a signed-in member reserves.
   */
  user?: (number | null) | User;
  name: string;
  email: string;
  note?: string | null;
  status?: ('confirmed' | 'waitlist' | 'cancelled') | null;
  website?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'frames';
        value: number | Frame;
      } | null)
    | ({
        relationTo: 'essays';
        value: number | Essay;
      } | null)
    | ({
        relationTo: 'albums';
        value: number | Album;
      } | null)
    | ({
        relationTo: 'walks';
        value: number | Walk;
      } | null)
    | ({
        relationTo: 'exhibitions';
        value: number | Exhibition;
      } | null)
    | ({
        relationTo: 'photocalls';
        value: number | Photocall;
      } | null)
    | ({
        relationTo: 'submissions';
        value: number | Submission;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'rsvps';
        value: number | Rsvp;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  profile?: T;
  membershipPlan?: T;
  membershipStatus?: T;
  membershipExpires?: T;
  memberSince?: T;
  newsletter?: T;
  pendingEmail?: T;
  pendingEmailToken?: T;
  pendingEmailExpires?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  memberNumber?: T;
  owner?: T;
  onRoster?: T;
  portrait?: T;
  bio?: T;
  roleTitle?: T;
  basedIn?: T;
  foundingCircle?: T;
  instagram?: T;
  website?: T;
  contactEmail?: T;
  showContact?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  visibility?: T;
  uploadedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "frames_select".
 */
export interface FramesSelect<T extends boolean = true> {
  image?: T;
  photographer?: T;
  creditOverride?: T;
  caption?: T;
  location?: T;
  year?: T;
  tags?: T;
  topPick?: T;
  sourceSubmission?: T;
  walk?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "essays_select".
 */
export interface EssaysSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  deck?: T;
  body?: T;
  leadFrame?: T;
  sequence?:
    | T
    | {
        frame?:
          | T
          | {
              frame?: T;
              captionOverride?: T;
              fullBleed?: T;
              id?: T;
              blockName?: T;
            };
        pair?:
          | T
          | {
              left?: T;
              right?: T;
              captionOverride?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              body?: T;
              id?: T;
              blockName?: T;
            };
      };
  contributors?: T;
  walks?: T;
  relatedPhotocall?: T;
  publishedDate?: T;
  tags?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "albums_select".
 */
export interface AlbumsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  intro?: T;
  images?: T;
  walks?: T;
  photographer?: T;
  creditOverride?: T;
  date?: T;
  publishedDate?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "walks_select".
 */
export interface WalksSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  date?: T;
  endTime?: T;
  meetingPoint?: T;
  route?: T;
  routeGeo?: T;
  routeMap?: T;
  capacity?: T;
  priceMember?: T;
  priceNonMember?: T;
  bookingUrl?: T;
  bookingStatus?: T;
  leader?: T;
  heroImage?: T;
  number?: T;
  essays?: T;
  frames?: T;
  albums?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exhibitions_select".
 */
export interface ExhibitionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  venue?: T;
  startDate?: T;
  endDate?: T;
  description?: T;
  heroImage?: T;
  frames?: T;
  relatedEssays?: T;
  partners?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photocalls_select".
 */
export interface PhotocallsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  theme?: T;
  heroImage?: T;
  opensAt?: T;
  closesAt?: T;
  maxImagesPerSubmission?: T;
  membersOnly?: T;
  terms?: T;
  status?: T;
  resultEssay?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  photocall?: T;
  submitter?: T;
  submitterName?: T;
  submitterEmail?: T;
  whereYouShoot?: T;
  title?: T;
  statement?: T;
  images?: T;
  agreedToTerms?: T;
  status?: T;
  reviewNotes?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  user?: T;
  type?: T;
  plan?: T;
  item?: T;
  amount?: T;
  joiningFee?: T;
  currency?: T;
  reference?: T;
  status?: T;
  paidAt?: T;
  coveredFrom?: T;
  coveredUntil?: T;
  provider?: T;
  providerRef?: T;
  note?: T;
  raw?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rsvps_select".
 */
export interface RsvpsSelect<T extends boolean = true> {
  walk?: T;
  user?: T;
  name?: T;
  email?: T;
  note?: T;
  status?: T;
  website?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteTitle?: string | null;
  contactEmail?: string | null;
  instagram?: string | null;
  facebook?: string | null;
  linkedin?: string | null;
  /**
   * Optional CMS override for the og:image default. The static /share/default.jpg ships with the frontend as the fallback.
   */
  defaultShareImage?: (number | null) | Media;
  /**
   * Short lines for the homepage ticker.
   */
  ticker?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  newsletterUrl?: string | null;
  announcement?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manifesto".
 */
export interface Manifesto {
  id: number;
  headword?: string | null;
  /**
   * The dictionary-style senses under the headword.
   */
  senses?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  lineage?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership".
 */
export interface Membership {
  id: number;
  benefits?:
    | {
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Once, in rand, for everyone who joins.
   */
  joiningFee?: number | null;
  /**
   * Per month, in rand.
   */
  priceMonthly?: number | null;
  /**
   * Per year, in rand.
   */
  priceAnnual?: number | null;
  /**
   * The kicker under the prices: what subscribing gets you.
   */
  priceNote?: string | null;
  /**
   * The open door, kept without a tier. Clear it to hide the line.
   */
  openDoorNote?: string | null;
  cardImage?: (number | null) | Media;
  /**
   * Leave empty: Join goes to sign-up on the site. Set only to send joining elsewhere.
   */
  joinUrl?: string | null;
  /**
   * EFT references read PREFIX-XXXXXX. Letters and digits only.
   */
  referencePrefix?: string | null;
  bank?: {
    accountName?: string | null;
    bankName?: string | null;
    accountNumber?: string | null;
    branchCode?: string | null;
    /**
     * Cheque, savings...
     */
    accountType?: string | null;
    paymentNote?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteTitle?: T;
  contactEmail?: T;
  instagram?: T;
  facebook?: T;
  linkedin?: T;
  defaultShareImage?: T;
  ticker?:
    | T
    | {
        text?: T;
        id?: T;
      };
  newsletterUrl?: T;
  announcement?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manifesto_select".
 */
export interface ManifestoSelect<T extends boolean = true> {
  headword?: T;
  senses?:
    | T
    | {
        text?: T;
        id?: T;
      };
  body?: T;
  lineage?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership_select".
 */
export interface MembershipSelect<T extends boolean = true> {
  benefits?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  joiningFee?: T;
  priceMonthly?: T;
  priceAnnual?: T;
  priceNote?: T;
  openDoorNote?: T;
  cardImage?: T;
  joinUrl?: T;
  referencePrefix?: T;
  bank?:
    | T
    | {
        accountName?: T;
        bankName?: T;
        accountNumber?: T;
        branchCode?: T;
        accountType?: T;
        paymentNote?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}